FROM althack/ros2:humble-full

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
USER root

# Install system utilities, networking tools, zsh and git
RUN apt update && apt install -y \
    wget \
    curl \
    git \
    cmake \
    ninja-build \
    build-essential \
    software-properties-common \
    ca-certificates \
    gnupg \
    lsb-release \
    python3 \
    python3-pip \
    iputils-ping \
    iproute2 \
    g++ \
    build-essential \
    libyaml-cpp-dev \
    libeigen3-dev \
    libboost-all-dev \
    libspdlog-dev \
    libfmt-dev \
    python3-colcon-common-extensions \
    nano \
    vim \
    terminator \
    rsync \
    && rm -rf /var/lib/apt/lists/*
    
# Install LLVM/Clang 18
RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 18 all && \
    rm llvm.sh

# Set Clang 18 as default
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100 && \
    update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-18 100 && \
    update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-18 100 && \
    update-alternatives --install /usr/bin/run-clang-tidy run-clang-tidy /usr/bin/run-clang-tidy-18 100

# Default compiler
ENV CC=/usr/bin/clang-18
ENV CXX=/usr/bin/clang++-18

# Install Unitree ROS2 Package
RUN apt update && apt install -y \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-rosidl-generator-dds-idl \
    libyaml-cpp-dev \
    && rm -rf /var/lib/apt/lists/*

# Upgrade 
RUN apt update && apt upgrade -y \
    && rm -rf /var/lib/apt/lists/*
    

RUN mkdir -p /unitree_ros2_ws/src
RUN mkdir -p /unitree_sdk2
RUN mkdir -p /unitree_sdk2_python

CMD ["/bin/bash"]
